version: '3'

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile_front
    volumes:
      - .:/zds
  zmarkdown:
    build:
      context: .
      dockerfile: Dockerfile_zmd
    working_dir: /zds/zmd/
    command: ["./docker_zmd_entrypoint.sh"]
    ports:
      - "27272:27272"
    expose:
      - "27272"
  db:
    image: "mysql:5"
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - dbdata:/var/lib/mysql
      - rundb:/var/run/mysqld
    environment:
      MYSQL_DATABASE: "zdsdb"
      MYSQL_USER: "zds"
      MYSQL_PASSWORD: "zds"
      MYSQL_ROOT_PASSWORD: "root"

  back:
    build:
      context: .
      dockerfile: Dockerfile_back
    working_dir: /zds
    command: ["./scripts/wait-for-it.sh", "-t", "90", "-s", "db:3306", "--", "./scripts/docker_dev_entrypoint.sh"]
    depends_on:
      - db
      - front
      - zmarkdown
      - elasticsearch
    volumes:
      - .:/zds
      - rundb:/var/run/mysqld:ro
    ports:
      - "${ZDS_ADDRESS:-127.0.0.1}:${ZDS_PORT:-8000}:8000"
    environment:
      # An optional comma-separated list of the hostnames to allow.
      # Sets Django’s ALLOWED_HOSTS configuration variable.
      - "ZDS_ALLOWED_HOSTS=${ZDS_ALLOWED_HOSTS:-*}"
      # Elasticsearch is enabled if this variable is nonempty
      - "ZDS_ELASTICSEARCH=${ZDS_ELASTICSEARCH}"

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.5.2"
    environment:
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  db:
  esdata:
  dbdata:
  rundb:
