- name: create zds virtual machine via vagrant
  hosts: all
  become: yes
  become_user: root
  remote_user: vagrant
  vars:
    - update_apt_cache: yes
  vars_files:
    - env_vars/local.yml
  roles:
    - ntp_role
    - base
    - github
    - nodejs_role
    - front
    - mysql_role
    - web
    - nginx_role
