- name: refresh source code
  synchronize:
    src: "../../../../"
    dest: "/opt/{{zds_app_name}}"
    rsync_opts:
      - "--exclude=.*"
      - "--exclude=*.pyc"
      - "--exclude=watchdog-build/"
      - "--exclude=contents-public/"
      - "--exclude=contents-private/"
      - "--exclude=dist/"
      - "--exclude=media/"
      - "--exclude=node_modules/"
      - "--exclude=deploy/"
      - "--exclude=doc/"
      - "--chown={{zds_unix_user}}:{{zds_unix_group}}"